# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import functions_pb2 as functions__pb2


class EpFunctionsStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.f1_noop = channel.unary_unary(
        '/functions.EpFunctions/f1_noop',
        request_serializer=functions__pb2.Empty.SerializeToString,
        response_deserializer=functions__pb2.Empty.FromString,
        )
    self.f2_square = channel.unary_unary(
        '/functions.EpFunctions/f2_square',
        request_serializer=functions__pb2.NumberRequest.SerializeToString,
        response_deserializer=functions__pb2.NumberReply.FromString,
        )
    self.f3_mean_8 = channel.unary_unary(
        '/functions.EpFunctions/f3_mean_8',
        request_serializer=functions__pb2.MeanRequest.SerializeToString,
        response_deserializer=functions__pb2.MeanReply.FromString,
        )
    self.f4_str_is_palindrome = channel.unary_unary(
        '/functions.EpFunctions/f4_str_is_palindrome',
        request_serializer=functions__pb2.PalindromeRequest.SerializeToString,
        response_deserializer=functions__pb2.PalindromeReply.FromString,
        )
    self.f5_exp_rep_string = channel.unary_unary(
        '/functions.EpFunctions/f5_exp_rep_string',
        request_serializer=functions__pb2.LongRequest.SerializeToString,
        response_deserializer=functions__pb2.LongReply.FromString,
        )
    self.f6_create_employee = channel.unary_unary(
        '/functions.EpFunctions/f6_create_employee',
        request_serializer=functions__pb2.Employee.SerializeToString,
        response_deserializer=functions__pb2.Empty.FromString,
        )
    self.f7_get_employee = channel.unary_unary(
        '/functions.EpFunctions/f7_get_employee',
        request_serializer=functions__pb2.EmployeeId.SerializeToString,
        response_deserializer=functions__pb2.Employee.FromString,
        )
    self.f8_get_employee_complete = channel.unary_unary(
        '/functions.EpFunctions/f8_get_employee_complete',
        request_serializer=functions__pb2.EmployeeId.SerializeToString,
        response_deserializer=functions__pb2.EmployeeComplete.FromString,
        )


class EpFunctionsServicer(object):
  """Interface exported by the server.
  """

  def f1_noop(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def f2_square(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def f3_mean_8(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def f4_str_is_palindrome(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def f5_exp_rep_string(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def f6_create_employee(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def f7_get_employee(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def f8_get_employee_complete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EpFunctionsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'f1_noop': grpc.unary_unary_rpc_method_handler(
          servicer.f1_noop,
          request_deserializer=functions__pb2.Empty.FromString,
          response_serializer=functions__pb2.Empty.SerializeToString,
      ),
      'f2_square': grpc.unary_unary_rpc_method_handler(
          servicer.f2_square,
          request_deserializer=functions__pb2.NumberRequest.FromString,
          response_serializer=functions__pb2.NumberReply.SerializeToString,
      ),
      'f3_mean_8': grpc.unary_unary_rpc_method_handler(
          servicer.f3_mean_8,
          request_deserializer=functions__pb2.MeanRequest.FromString,
          response_serializer=functions__pb2.MeanReply.SerializeToString,
      ),
      'f4_str_is_palindrome': grpc.unary_unary_rpc_method_handler(
          servicer.f4_str_is_palindrome,
          request_deserializer=functions__pb2.PalindromeRequest.FromString,
          response_serializer=functions__pb2.PalindromeReply.SerializeToString,
      ),
      'f5_exp_rep_string': grpc.unary_unary_rpc_method_handler(
          servicer.f5_exp_rep_string,
          request_deserializer=functions__pb2.LongRequest.FromString,
          response_serializer=functions__pb2.LongReply.SerializeToString,
      ),
      'f6_create_employee': grpc.unary_unary_rpc_method_handler(
          servicer.f6_create_employee,
          request_deserializer=functions__pb2.Employee.FromString,
          response_serializer=functions__pb2.Empty.SerializeToString,
      ),
      'f7_get_employee': grpc.unary_unary_rpc_method_handler(
          servicer.f7_get_employee,
          request_deserializer=functions__pb2.EmployeeId.FromString,
          response_serializer=functions__pb2.Employee.SerializeToString,
      ),
      'f8_get_employee_complete': grpc.unary_unary_rpc_method_handler(
          servicer.f8_get_employee_complete,
          request_deserializer=functions__pb2.EmployeeId.FromString,
          response_serializer=functions__pb2.EmployeeComplete.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'functions.EpFunctions', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
