# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: functions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='functions.proto',
  package='functions',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x66unctions.proto\x12\tfunctions\"\x07\n\x05\x45mpty\"\x1c\n\rNumberRequest\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x1a\n\x0bNumberReply\x12\x0b\n\x03num\x18\x01 \x01(\x05\"\x1a\n\x0bLongRequest\x12\x0b\n\x03num\x18\x01 \x01(\t\"\x18\n\tLongReply\x12\x0b\n\x03num\x18\x01 \x01(\t\"W\n\x08\x45mployee\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12$\n\x07manager\x18\x04 \x01(\x0b\x32\x13.functions.Employee\"\x18\n\nEmployeeId\x12\n\n\x02id\x18\x01 \x01(\x05\"2\n\x10\x45mployeeComplete\x12\x1e\n\x01\x65\x18\x01 \x01(\x0b\x32\x13.functions.Employee\"m\n\x0bMeanRequest\x12\n\n\x02n1\x18\x01 \x01(\x03\x12\n\n\x02n2\x18\x02 \x01(\x03\x12\n\n\x02n3\x18\x03 \x01(\x03\x12\n\n\x02n4\x18\x04 \x01(\x03\x12\n\n\x02n5\x18\x05 \x01(\x03\x12\n\n\x02n6\x18\x06 \x01(\x03\x12\n\n\x02n7\x18\x07 \x01(\x03\x12\n\n\x02n8\x18\x08 \x01(\x03\"\x17\n\tMeanReply\x12\n\n\x02n1\x18\x01 \x01(\x03\"\'\n\x11PalindromeRequest\x12\x12\n\npalindrome\x18\x01 \x01(\t\"%\n\x0fPalindromeReply\x12\x12\n\npalindrome\x18\x01 \x01(\x08\x32\xa7\x04\n\x0b\x45pFunctions\x12/\n\x07\x66\x31_noop\x12\x10.functions.Empty\x1a\x10.functions.Empty\"\x00\x12?\n\tf2_square\x12\x18.functions.NumberRequest\x1a\x16.functions.NumberReply\"\x00\x12;\n\tf3_mean_8\x12\x16.functions.MeanRequest\x1a\x14.functions.MeanReply\"\x00\x12R\n\x14\x66\x34_str_is_palindrome\x12\x1c.functions.PalindromeRequest\x1a\x1a.functions.PalindromeReply\"\x00\x12\x43\n\x11\x66\x35_exp_rep_string\x12\x16.functions.LongRequest\x1a\x14.functions.LongReply\"\x00\x12=\n\x12\x66\x36_create_employee\x12\x13.functions.Employee\x1a\x10.functions.Empty\"\x00\x12?\n\x0f\x66\x37_get_employee\x12\x15.functions.EmployeeId\x1a\x13.functions.Employee\"\x00\x12P\n\x18\x66\x38_get_employee_complete\x12\x15.functions.EmployeeId\x1a\x1b.functions.EmployeeComplete\"\x00\x42\x36\n\x1bio.grpc.examples.routeguideB\x0fRouteGuideProtoP\x01\xa2\x02\x03RTGb\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='functions.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=37,
)


_NUMBERREQUEST = _descriptor.Descriptor(
  name='NumberRequest',
  full_name='functions.NumberRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='functions.NumberRequest.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=67,
)


_NUMBERREPLY = _descriptor.Descriptor(
  name='NumberReply',
  full_name='functions.NumberReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='functions.NumberReply.num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=95,
)


_LONGREQUEST = _descriptor.Descriptor(
  name='LongRequest',
  full_name='functions.LongRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='functions.LongRequest.num', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=123,
)


_LONGREPLY = _descriptor.Descriptor(
  name='LongReply',
  full_name='functions.LongReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='num', full_name='functions.LongReply.num', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=149,
)


_EMPLOYEE = _descriptor.Descriptor(
  name='Employee',
  full_name='functions.Employee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='functions.Employee.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='functions.Employee.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='functions.Employee.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='manager', full_name='functions.Employee.manager', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=238,
)


_EMPLOYEEID = _descriptor.Descriptor(
  name='EmployeeId',
  full_name='functions.EmployeeId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='functions.EmployeeId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=264,
)


_EMPLOYEECOMPLETE = _descriptor.Descriptor(
  name='EmployeeComplete',
  full_name='functions.EmployeeComplete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='e', full_name='functions.EmployeeComplete.e', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=316,
)


_MEANREQUEST = _descriptor.Descriptor(
  name='MeanRequest',
  full_name='functions.MeanRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='functions.MeanRequest.n1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n2', full_name='functions.MeanRequest.n2', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n3', full_name='functions.MeanRequest.n3', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n4', full_name='functions.MeanRequest.n4', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n5', full_name='functions.MeanRequest.n5', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n6', full_name='functions.MeanRequest.n6', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n7', full_name='functions.MeanRequest.n7', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n8', full_name='functions.MeanRequest.n8', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=427,
)


_MEANREPLY = _descriptor.Descriptor(
  name='MeanReply',
  full_name='functions.MeanReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='n1', full_name='functions.MeanReply.n1', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=452,
)


_PALINDROMEREQUEST = _descriptor.Descriptor(
  name='PalindromeRequest',
  full_name='functions.PalindromeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='palindrome', full_name='functions.PalindromeRequest.palindrome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=493,
)


_PALINDROMEREPLY = _descriptor.Descriptor(
  name='PalindromeReply',
  full_name='functions.PalindromeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='palindrome', full_name='functions.PalindromeReply.palindrome', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=495,
  serialized_end=532,
)

_EMPLOYEE.fields_by_name['manager'].message_type = _EMPLOYEE
_EMPLOYEECOMPLETE.fields_by_name['e'].message_type = _EMPLOYEE
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['NumberRequest'] = _NUMBERREQUEST
DESCRIPTOR.message_types_by_name['NumberReply'] = _NUMBERREPLY
DESCRIPTOR.message_types_by_name['LongRequest'] = _LONGREQUEST
DESCRIPTOR.message_types_by_name['LongReply'] = _LONGREPLY
DESCRIPTOR.message_types_by_name['Employee'] = _EMPLOYEE
DESCRIPTOR.message_types_by_name['EmployeeId'] = _EMPLOYEEID
DESCRIPTOR.message_types_by_name['EmployeeComplete'] = _EMPLOYEECOMPLETE
DESCRIPTOR.message_types_by_name['MeanRequest'] = _MEANREQUEST
DESCRIPTOR.message_types_by_name['MeanReply'] = _MEANREPLY
DESCRIPTOR.message_types_by_name['PalindromeRequest'] = _PALINDROMEREQUEST
DESCRIPTOR.message_types_by_name['PalindromeReply'] = _PALINDROMEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.Empty)
  ))
_sym_db.RegisterMessage(Empty)

NumberRequest = _reflection.GeneratedProtocolMessageType('NumberRequest', (_message.Message,), dict(
  DESCRIPTOR = _NUMBERREQUEST,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.NumberRequest)
  ))
_sym_db.RegisterMessage(NumberRequest)

NumberReply = _reflection.GeneratedProtocolMessageType('NumberReply', (_message.Message,), dict(
  DESCRIPTOR = _NUMBERREPLY,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.NumberReply)
  ))
_sym_db.RegisterMessage(NumberReply)

LongRequest = _reflection.GeneratedProtocolMessageType('LongRequest', (_message.Message,), dict(
  DESCRIPTOR = _LONGREQUEST,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.LongRequest)
  ))
_sym_db.RegisterMessage(LongRequest)

LongReply = _reflection.GeneratedProtocolMessageType('LongReply', (_message.Message,), dict(
  DESCRIPTOR = _LONGREPLY,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.LongReply)
  ))
_sym_db.RegisterMessage(LongReply)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEE,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.Employee)
  ))
_sym_db.RegisterMessage(Employee)

EmployeeId = _reflection.GeneratedProtocolMessageType('EmployeeId', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEEID,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.EmployeeId)
  ))
_sym_db.RegisterMessage(EmployeeId)

EmployeeComplete = _reflection.GeneratedProtocolMessageType('EmployeeComplete', (_message.Message,), dict(
  DESCRIPTOR = _EMPLOYEECOMPLETE,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.EmployeeComplete)
  ))
_sym_db.RegisterMessage(EmployeeComplete)

MeanRequest = _reflection.GeneratedProtocolMessageType('MeanRequest', (_message.Message,), dict(
  DESCRIPTOR = _MEANREQUEST,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.MeanRequest)
  ))
_sym_db.RegisterMessage(MeanRequest)

MeanReply = _reflection.GeneratedProtocolMessageType('MeanReply', (_message.Message,), dict(
  DESCRIPTOR = _MEANREPLY,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.MeanReply)
  ))
_sym_db.RegisterMessage(MeanReply)

PalindromeRequest = _reflection.GeneratedProtocolMessageType('PalindromeRequest', (_message.Message,), dict(
  DESCRIPTOR = _PALINDROMEREQUEST,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.PalindromeRequest)
  ))
_sym_db.RegisterMessage(PalindromeRequest)

PalindromeReply = _reflection.GeneratedProtocolMessageType('PalindromeReply', (_message.Message,), dict(
  DESCRIPTOR = _PALINDROMEREPLY,
  __module__ = 'functions_pb2'
  # @@protoc_insertion_point(class_scope:functions.PalindromeReply)
  ))
_sym_db.RegisterMessage(PalindromeReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\033io.grpc.examples.routeguideB\017RouteGuideProtoP\001\242\002\003RTG'))

_EPFUNCTIONS = _descriptor.ServiceDescriptor(
  name='EpFunctions',
  full_name='functions.EpFunctions',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=535,
  serialized_end=1086,
  methods=[
  _descriptor.MethodDescriptor(
    name='f1_noop',
    full_name='functions.EpFunctions.f1_noop',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='f2_square',
    full_name='functions.EpFunctions.f2_square',
    index=1,
    containing_service=None,
    input_type=_NUMBERREQUEST,
    output_type=_NUMBERREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='f3_mean_8',
    full_name='functions.EpFunctions.f3_mean_8',
    index=2,
    containing_service=None,
    input_type=_MEANREQUEST,
    output_type=_MEANREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='f4_str_is_palindrome',
    full_name='functions.EpFunctions.f4_str_is_palindrome',
    index=3,
    containing_service=None,
    input_type=_PALINDROMEREQUEST,
    output_type=_PALINDROMEREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='f5_exp_rep_string',
    full_name='functions.EpFunctions.f5_exp_rep_string',
    index=4,
    containing_service=None,
    input_type=_LONGREQUEST,
    output_type=_LONGREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='f6_create_employee',
    full_name='functions.EpFunctions.f6_create_employee',
    index=5,
    containing_service=None,
    input_type=_EMPLOYEE,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='f7_get_employee',
    full_name='functions.EpFunctions.f7_get_employee',
    index=6,
    containing_service=None,
    input_type=_EMPLOYEEID,
    output_type=_EMPLOYEE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='f8_get_employee_complete',
    full_name='functions.EpFunctions.f8_get_employee_complete',
    index=7,
    containing_service=None,
    input_type=_EMPLOYEEID,
    output_type=_EMPLOYEECOMPLETE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EPFUNCTIONS)

DESCRIPTOR.services_by_name['EpFunctions'] = _EPFUNCTIONS

# @@protoc_insertion_point(module_scope)
